name: modu_3_dart_study
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0



# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.19.1
  intl: ^0.18.1
  json_annotation: ^4.9.0
  http: ^1.3.0
  freezed_annotation: ^3.0.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  freezed: ^3.0.4
